# Generated by Django 3.2.7 on 2021-10-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20211013_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='original_bag',
            new_name='original_cart',
        ),
    ]
