# Generated by Django 3.2.7 on 2021-10-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('checkout', '0009_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_id',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
