# Generated by Django 3.2.7 on 2021-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='f_parcel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
