# Generated by Django 3.2.7 on 2021-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/items/'),
        ),
    ]
